from pptx import Presentation
import os

def create_ppt_from_text(topic: str, save_path: str = None):
    prs = Presentation()
    slide_layout = prs.slide_layouts[1]  # Title & Content
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = topic
    slide.placeholders[1].text = f"Generated by AI for: {topic}"
    
    if not save_path:
        save_path = os.path.join(os.getcwd(), "generated_ppt.pptx")
    
    prs.save(save_path)
    return save_path
